<h2>Staff Login</h2>
<form action="/admin/login" method="post">
	<table>
	<tr>
		<td>Username:</td>
		<td>
		<input type="text" name="username" maxlength="30" value="" />
		</td>
	</tr>
	<tr>
		<td>Password:</td>
		<td>
		<input type="password" name="password" maxlength="30" value="" />
		</td>
	</tr>
	<tr>
		<td colspan="2">
		<input type="submit" name="submit" value="Login" />
		</td>
	</tr>
	</table>
</form>