<h1>Редактировать категорию</h1>
<p><a href="/admin/category/">назад</a></p>
<form action="<?php echo $_SERVER['REQUEST_URI']; ?>" method="post">
	<p>Название: <input type="text" name="name" value="<?php echo $category->name;?>" /></p>
	<p>Путь    : <input type="text" name="path" value="<?php echo $category->path;?>" /></p>
	<p>Видимость: 
	<select name="visible">
	<option <?php echo ($category->visible == '1')?'selected':''; ?> value="1">видимая</option>
	<option <?php echo ($category->visible == '0')?'selected':''; ?> value="0">не видимая</option>
	</select>
	
	</p>
	<p><input type="submit" value="Сохранить" /></p>
</form>


<hr />
<?php AlertWidget::run(); ?>
<h2>Подкатегории</h2>
<form action="/admin/category/create/category_id/<?php echo $category->id;?>" method="post">
<table class="table table-bordered table-hover">
	<tr>
		<th>ID</th><th>Название</th><th>Путь</th><th>Таблица объявлений</th><th>Родитель</th><th>ред.</th><th>уд.</th>
	</tr>

	<?php if($subcategories){ ?>
	<?php foreach ($subcategories as $subcategory) { ?>
	<tr>
		<td><?php echo $subcategory->id; ?></td>
		<td><?php echo $subcategory->name; ?></td>
		<td><?php echo $subcategory->path; ?></td>
		<td><?php echo $subcategory->table_ads; ?></td>
		<td><?php echo $subcategory->parent; ?></td>
		<td><a href="/admin/category/edit/id/<?php echo $subcategory->id; ?>"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a></td>
		<td><a href="/admin/category/delete/id/<?php echo $subcategory->id; ?>"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a></td>
	</tr>
	<?php } ?>	
	<?php } ?>
	<tr>
		<td><span class="glyphicon glyphicon-plus" aria-hidden="true"></span></td>		
		<td><input type="text" name="name" value="" /></td>
		<td><input type="text" name="path" value="" /></td>
		<td><input type="text" name="table" value="" /></td>
		<td><?php echo $category->id;?></td>	
		<td><input type="submit" value="Сохранить" /></td>
	</tr>
</table>
</form>
