<h1>Категории</h1>
<p><a href="/admin/category/create">Добавить категорию</a></p>
<?php AlertWidget::run(); ?>
<table class="table table-bordered table-hover">
	<tr>
		<th>ID</th><th>Название</th><th>Путь</th><th>Таблица объявлений</th><th>Видимость</th><th>ред.</th><th>уд.</th>
	</tr>
	<?php foreach($categories as $category){ ?>
	<tr>
		<td><?php echo $category->id; ?></td>
		<td><?php echo $category->name; ?></td>
		<td><?php echo $category->path; ?></td>
		<td><?php echo $category->table_ads; ?></td>
		<td><?php echo $category->visible; ?></td>
		<td><a href="/admin/category/edit/id/<?php echo $category->id; ?>"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a></td>
		<td><a href="/admin/category/delete/id/<?php echo $category->id; ?>"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a></td>
	</tr>
	<?php } ?>
</table>
<p><a href="/admin/category/create">Добавить категорию</a></p>